<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Loterie</title>
   <meta charset="utf-8">
   <link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
   <header>
      <h1>Bienvenue à la loterie !!!</h1>
   </header>
   <main>
      <h2>Voici le tirage d'aujourd'hui :</h2>
      <section>
         <div>
            <?= $tirage[0];?>
         </div>
         <div>
            <?php echo $tirage[1];?>
         </div>
         <div>
            <?php echo $tirage[2];?>
         </div>
         <div>
            <?php echo $tirage[3];?>
         </div>
         <div>
            <?php echo $tirage[4];?>
         </div>
         <div>
            <?php echo $tirage[5];?>
         </div>
      </section>
   </main>

</body>
</html>